name: Build and Deploy
on: # 当master分支有push操作时，执行jobs
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境
    permissions:
      contents: write # 写入权限
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 # 告知使用的action版本

      - name: Lock npm version # 指定node版本
        uses: actions/setup-node@v3 
        with:
          node-version: 16.18.0

      - name: Install and Build # 安装依赖、build打包
        run: |
          npm i -g pnpm
          pnpm run init
          pnpm run build:doc
        env:
          NODE_OPTIONS: '--max_old_space_size=4096' # node分配区？

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3 # 使用这个发布工具发布到githubio，告知分支、打包目录
        with:
          BRANCH: gh-pages
          FOLDER: dist
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
