name: Publish Package to npmjs

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
        env:
          NODE_OPTIONS: '--max_old_space_size=4096' # node分配区？

      - name: Install and Build and Publish to npmjs # 安装依赖、build打包
        run: |
          npm i -g pnpm
          pnpm run init
          npm run pub
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
